import {
  AlignLeft,
  AppWindow,
  BadgeCheck,
  ClipboardList,
  Compass,
  FileText,
  Gauge,
  Handshake,
  KeyRound,
  LayoutGrid,
  MousePointerClick,
  Palette,
  Phone,
  Rocket,
  Search,
  Smartphone,
  Target,
  type LucideIcon,
} from "lucide-react";

const ICONS_BY_TITLE: Record<string, LucideIcon> = {
  "Look credible": BadgeCheck,
  "Work on a phone": Smartphone,
  "Make the offer clear": AlignLeft,
  "Give them a next step": MousePointerClick,
  Strategy: Compass,
  "Custom design": Palette,
  "Custom Design": Palette,
  "Built for phones first": Smartphone,
  "Mobile First": Smartphone,
  "Clear next step": MousePointerClick,
  Speed: Gauge,
  Performance: Gauge,
  "SEO foundation": Search,
  "SEO Foundation": Search,
  "If you need a new website": AppWindow,
  "If you already have a website": Search,
  "What you walk away with": ClipboardList,
  "If we work together": Handshake,
  "Built around the sale": Target,
  "One job per screen": LayoutGrid,
  "Phone first": Smartphone,
  "Custom-coded, yours to keep": KeyRound,
  "Quote path dies on mobile": Smartphone,
  "Buried phone number": MousePointerClick,
  "Looks finished, loses the job": BadgeCheck,
  "Slow pages, weak search": Gauge,
  "Call & quote path": MousePointerClick,
  "Conversion Path": MousePointerClick,
  "You own the website": KeyRound,
  "You Own It": KeyRound,
  "Mobile usability": Smartphone,
  Mobile: Smartphone,
  Calls: Phone,
  Search: Search,
  "Speed and performance": Gauge,
  "Call and quote conversion path": MousePointerClick,
  "SEO and search foundation": Search,
  "Tracking and lead capture": ClipboardList,
  Plan: ClipboardList,
  Build: AppWindow,
  Launch: Rocket,
};

export function iconForLandingPoint(title: string): LucideIcon {
  return ICONS_BY_TITLE[title] ?? FileText;
}
