import { localeContent } from "@/i18n/locale-content";
import type { Locale } from "@/i18n/routing";

export type ExampleViewpoint = "phone" | "tablet" | "desktop";

const en = {
  hint: "Same company. Scroll and tap through the pages.",
  switchLabel: "Which site",
  beforeCaption: "Old site",
  beforeNote: "A stock WordPress theme",
  afterCaption: "New site",
  afterNote: "Custom coded for the crew",
  frameBefore: "Old site for Greenfield Lawn Care, a stock WordPress theme",
  frameAfter: "New site for Greenfield Lawn Care, custom coded",
  wp: {
    domain: "greenfieldlawncare.com",
    free: "Free Estimates",
    call: "Call now",
    licensed: "Licensed & Insured",
    menu: "Menu",
    close: "Close menu",
    nav: [
      { id: "home" as const, label: "Home", path: "" },
      { id: "about" as const, label: "About", path: "/about-us" },
      { id: "services" as const, label: "Services", path: "/our-services" },
      { id: "contact" as const, label: "Contact", path: "/contact-us" },
    ],
    slides: [
      {
        kicker: "Welcome to our website",
        title: "Quality Landscaping You Can Trust",
        body: "Family owned since 1998. Call for more information.",
      },
      {
        kicker: "Serving the area",
        title: "Lawn Care, Landscaping, and More",
        body: "We offer a variety of services. Contact us today.",
      },
      {
        kicker: "Free estimates",
        title: "Call For Your Free Estimate",
        body: "Family owned and operated. Click below.",
      },
    ],
    click: "Click Here",
    services: [
      {
        id: "lawn",
        title: "Lawn Care",
        body: "We provide quality lawn care services for residential and commercial properties. Call for more information.",
      },
      {
        id: "scape",
        title: "Landscaping",
        body: "Our landscaping services include a variety of options to fit your needs. Contact us for details.",
      },
      {
        id: "hard",
        title: "Hardscaping",
        body: "We install patios, walks, and more. Please call the office for pricing and availability.",
      },
    ],
    welcomeTitle: "Welcome to Greenfield Lawn Care",
    welcome: [
      "Greenfield Lawn Care is a family owned company that has been serving the area since 1998. We strive to provide quality service at a competitive price.",
      "Lawn care, landscaping, and hardscaping are all available. Browse the site and contact us with any questions.",
    ],
    blogTitle: "From the blog",
    blogPost: "5 Tips for a Greener Lawn This Spring",
    blogMore: "Read More",
    blogLess: "Close",
    blogBody:
      "Spring is a great time to think about your lawn. Water regularly, mow at the right height, and call a professional for more information. Thank you for visiting our blog.",
    searchLabel: "Search",
    searchButton: "Search",
    searchEmpty: "Nothing matched that search.",
    recentTitle: "Recent posts",
    recent: ["5 Tips for a Greener Lawn This Spring", "Hello world!"],
    categoriesTitle: "Categories",
    categories: ["Lawn Care", "Uncategorized"],
    metaTitle: "Meta",
    login: "Log in",
    rss: "Entries RSS",
    loginNote: "Sample site. There is no login.",
    aboutTitle: "About Us",
    about: [
      "Greenfield Lawn Care has been family owned and operated since 1998. We take pride in customer satisfaction and quality workmanship.",
      "Our team is dedicated to meeting your outdoor needs. Call today for more information about our services.",
    ],
    servicesTitle: "Our Services",
    servicesIntro:
      "Below is a list of the services we offer. Click a button to contact the office.",
    contactTitle: "Contact Us",
    contactIntro: "Fill out the form below and we will get back to you as soon as possible.",
    phoneLabel: "Phone",
    phone: "(555) 555-0199",
    address: "123 Main Street, Springfield",
    form: {
      name: "Name",
      email: "Email",
      message: "Message",
      send: "Submit",
      error: "Please fill in the required fields.",
      thanks: "Thank you. Your message has been sent.",
    },
    footer: "Proudly powered by WordPress",
  },
  nx: {
    domain: "greenfieldlawncare.com",
    menu: "Menu",
    close: "Close menu",
    home: "Home",
    quote: "Get a quote",
    call: "Call now",
    trade: "Lawn Care",
    kicker: "Design-build crews",
    title: "Yards that look finished.",
    lede: "Design, build, and seasonal care from one crew.",
    rating: "4.9 from homeowners on the route",
    trust: ["Licensed", "Insured", "Local crews"],
    stats: [
      { value: "1998", label: "Family owned" },
      { value: "5", label: "Towns" },
      { value: "Weekly", label: "Mow day" },
    ],
    introEyebrow: "One crew",
    introTitle: "Drawn, built, and mowed by the same people.",
    introBody:
      "The install does not get handed to a different company. Greenfield stays on the lawn after the patio is in.",
    introLink: "About the crew",
    marquee: ["Lawn care", "Fertilization", "Aeration", "Design", "Hardscape", "Irrigation", "Licensed", "Insured"],
    servicesLabel: "Services",
    servicesLead: "Eight ways the crew works a yard. One quote covers the ones you need.",
    featuredLabel: "Before anyone digs",
    alsoLabel: "Also on the truck",
    processTitle: "How a job starts",
    steps: [
      {
        title: "Walk the yard",
        body: "We measure the lawn, the beds, and what you want left alone.",
      },
      {
        title: "Price the drawing",
        body: "The quote names the work. You can walk the plan before anyone starts.",
      },
      {
        title: "Stay on the route",
        body: "After the install, mowing and cleanup stay with this crew.",
      },
    ],
    spotlightKicker: "Springfield",
    spotlightTitle: "A patio from the same drawing.",
    spotlightBody: "Pavers, the walk, and the beds were on the plan the homeowner approved.",
    spotlightLink: "See recent work",
    reviewsTitle: "From yards on the route",
    reviews: [
      {
        quote: "They walked the yard, left a plan, and built what was on it.",
        by: "Homeowner, Springfield",
      },
      {
        quote: "The mow shows up on the day they named. Edging and the blow-off are part of that visit.",
        by: "Homeowner, Riverside",
      },
    ],
    areasLabel: "Towns on the route",
    areasLead: "Design and the weekly route both stop here.",
    areasLink: "See service areas",
    ctaTitle: "Have the yard walked.",
    ctaBody: "Say which town and what the yard needs. We call back with a time.",
    phoneLabel: "Call",
    phone: "(555) 555-0199",
    aboutNav: "About",
    galleryNav: "Gallery",
    areasNav: "Areas",
    contactNav: "Contact",
    services: [
      {
        id: "lawn" as const,
        path: "/lawn-care",
        nav: "Lawn care",
        card: "Weekly mowing, edging, and a blow-off on a set day.",
        title: "Lawn care in Springfield",
        lede: "Mowing, edging, and blowing on the same day each week.",
        includes: [
          "Weekly mowing in season",
          "Edging along walks and beds",
          "Clippings blown off hard surfaces",
          "A route through five towns",
        ],
        faqs: [
          {
            q: "Is the visit weekly?",
            a: "In season, yes. Weather can move the day. It does not drop off the route.",
          },
          {
            q: "Do you mow outside Springfield?",
            a: "The route includes Riverside, Fairview, Greenville, and Oakwood.",
          },
        ],
      },
      {
        id: "feed" as const,
        path: "/fertilization",
        nav: "Fertilization",
        card: "Five visits for feed and weeds, on their own route.",
        title: "Fertilization and weed control",
        lede: "Five visits, timed to the season, instead of one spray and a hope.",
        includes: [
          "Early spring feed",
          "Broadleaf weed control",
          "A summer check for grubs",
          "A fall feed before dormancy",
        ],
        faqs: [
          {
            q: "Is this the same visit as mowing?",
            a: "No. Fertilization is its own route, with its own quote.",
          },
          {
            q: "Do you treat the whole yard?",
            a: "The plan covers the lawn. Beds and hardscape stay out of the spray.",
          },
        ],
      },
      {
        id: "aeration" as const,
        path: "/aeration",
        nav: "Aeration",
        card: "Cores in early fall, then seed on the thin spots.",
        title: "Core aeration and seeding",
        lede: "Cores pulled in early fall, then seed on the thin spots.",
        includes: [
          "Core aeration",
          "Seed on worn areas",
          "A light topdress where the soil is poor",
          "A look after the first mow",
        ],
        faqs: [
          {
            q: "When do you aerate?",
            a: "Early fall, while the soil is still warm.",
          },
          {
            q: "Can I mow right after?",
            a: "Wait until the seed has taken. The crew will say when.",
          },
        ],
      },
      {
        id: "cleanup" as const,
        path: "/seasonal-cleanup",
        nav: "Cleanup",
        card: "Beds cut back, leaves hauled, yard opened or closed.",
        title: "Spring and fall cleanup",
        lede: "Beds cut back, leaves hauled, and the yard opened or closed for the season.",
        includes: ["Bed cutbacks", "Leaf removal", "Haul-away", "A walk-through when the crew finishes"],
        faqs: [
          {
            q: "Is cleanup part of mowing?",
            a: "Weekly blowing is. A full seasonal cleanup is a separate visit.",
          },
          {
            q: "Do you haul the debris?",
            a: "Yes. It leaves with the crew.",
          },
        ],
      },
      {
        id: "design" as const,
        path: "/landscape-design",
        nav: "Design",
        card: "A measured plan you can walk before the crew digs.",
        title: "Landscape design in Springfield",
        lede: "A measured plan you can walk before the crew starts.",
        includes: [
          "Site walk and measurements",
          "Beds, lawn, and plants placed",
          "Hardscape on the same drawing",
          "A quote tied to that plan",
        ],
        faqs: [
          {
            q: "Do you design before you build?",
            a: "Yes. The price follows the drawing.",
          },
          {
            q: "Which towns are on the design route?",
            a: "Springfield, Riverside, Fairview, Greenville, and Oakwood.",
          },
        ],
      },
      {
        id: "planting" as const,
        path: "/planting",
        nav: "Planting",
        card: "Shrubs, perennials, and mulch set from the plan.",
        title: "Planting and mulch",
        lede: "Shrubs, perennials, and mulch set from the plan, not guessed at the nursery.",
        includes: ["Shrubs and perennials", "Bed edging", "Mulch to a set depth", "A first-season watering note"],
        faqs: [
          {
            q: "Do I pick the plants?",
            a: "You can. Or the plan names them and the crew buys them.",
          },
          {
            q: "When do you plant?",
            a: "Spring and fall. Summer installs only if watering is already in place.",
          },
        ],
      },
      {
        id: "hardscape" as const,
        path: "/hardscaping",
        nav: "Hardscape",
        card: "Patios, walks, and walls from the same crew.",
        title: "Patios, walks, and walls",
        lede: "Pavers and stone, built by the crew that drew the plan.",
        includes: ["Paver patios", "Front walks", "Retaining walls", "Steps and edges"],
        faqs: [
          {
            q: "Can you build from a plan I already have?",
            a: "Yes. If you want the crew to draw it, start with design.",
          },
          {
            q: "When do patios go in?",
            a: "Through the building season. The quote names the window.",
          },
        ],
      },
      {
        id: "irrigation" as const,
        path: "/irrigation",
        nav: "Irrigation",
        card: "New zones where the lawn needs them, plus a blowout.",
        title: "Irrigation and winterization",
        lede: "New zones where the lawn needs them, and a blowout before the first hard freeze.",
        includes: ["Zone layout", "Head replacement", "Controller setup", "Fall blowout"],
        faqs: [
          {
            q: "Do you service systems you did not install?",
            a: "Yes. The quote starts with a walk of the existing zones.",
          },
          {
            q: "When is the blowout?",
            a: "Before the first hard freeze, on a scheduled day.",
          },
        ],
      },
    ],
    includedLabel: "What's included",
    faqLabel: "Questions",
    otherLabel: "Other services",
    townsTitle: "Towns this crew covers",
    townsLede: "Design, hardscape, and lawn care from one crew in these towns.",
    towns: [
      { name: "Springfield", body: "Design, patios, and the weekly mowing route." },
      { name: "Riverside", body: "Hardscape installs and seasonal lawn care." },
      { name: "Fairview", body: "Smaller yards, with the plan drawn first." },
      { name: "Greenville", body: "On the route for mowing and cleanup." },
      { name: "Oakwood", body: "Lawn care and smaller hardscape jobs." },
    ],
    galleryTitle: "Recent work",
    galleryLede: "Patios, walks, and lawns the same crew finished.",
    projects: [
      { title: "Paver patio", place: "Springfield", image: "patio" as const, focus: "center 48%" },
      { title: "Front walk and beds", place: "Riverside", image: "walk" as const, focus: "center 18%" },
      { title: "Weekly lawn route", place: "Fairview", image: "house" as const, focus: "center 70%" },
      { title: "Retaining wall", place: "Springfield", image: "wall" as const, focus: "center 55%" },
    ],
    aboutTitle: "One crew since 1998",
    about: [
      "Greenfield draws the plan, builds the hardscape, and stays on the lawn route. It is the same people from the first walk to the weekly cut.",
      "Licensed and insured. The work is in Springfield and the towns next to it.",
    ],
    contactTitle: "Get a quote",
    contactLede: "Tell us the town and the work. We call back with a time to walk the yard.",
    form: {
      name: "Name",
      phone: "Phone",
      email: "Email",
      need: "What do you need?",
      message: "The yard, in a sentence",
      send: "Request a quote",
      error: "Add a name and a way to reach you.",
      thanks: "This form is part of the example. Nothing was sent.",
    },
    footerBlurb: "Design, hardscape, and lawn care from one crew.",
    since: "Family owned since 1998",
    footerServices: "Services",
    footerCompany: "Company",
    footerAreas: "Areas",
  },
};

const es = {
  hint: "La misma empresa. Desplázate y abre las páginas.",
  switchLabel: "Qué sitio",
  beforeCaption: "Sitio anterior",
  beforeNote: "Un tema de WordPress de catálogo",
  afterCaption: "Sitio nuevo",
  afterNote: "Hecho a medida para el equipo",
  frameBefore: "Sitio anterior de Greenfield Lawn Care, un tema de WordPress",
  frameAfter: "Sitio nuevo de Greenfield Lawn Care, hecho a medida",
  wp: {
    domain: "greenfieldlawncare.com",
    free: "Presupuestos gratis",
    call: "Llama ahora",
    licensed: "Con licencia y seguro",
    menu: "Menú",
    close: "Cerrar menú",
    nav: [
      { id: "home" as const, label: "Inicio", path: "" },
      { id: "about" as const, label: "Nosotros", path: "/about-us" },
      { id: "services" as const, label: "Servicios", path: "/our-services" },
      { id: "contact" as const, label: "Contacto", path: "/contact-us" },
    ],
    slides: [
      {
        kicker: "Bienvenido a nuestro sitio",
        title: "Jardinería de calidad en la que puedes confiar",
        body: "Familia desde 1998. Llama para más información.",
      },
      {
        kicker: "En la zona",
        title: "Césped, jardinería y más",
        body: "Ofrecemos una variedad de servicios. Contáctanos hoy.",
      },
      {
        kicker: "Presupuestos gratis",
        title: "Llama para tu presupuesto gratis",
        body: "Empresa familiar. Haz clic abajo.",
      },
    ],
    click: "Clic aquí",
    services: [
      {
        id: "lawn",
        title: "Césped",
        body: "Ofrecemos servicios de césped para casas y negocios. Llama para más información.",
      },
      {
        id: "scape",
        title: "Jardinería",
        body: "Nuestros servicios de jardinería incluyen varias opciones. Contáctanos para detalles.",
      },
      {
        id: "hard",
        title: "Pavimento",
        body: "Instalamos patios, caminos y más. Llama a la oficina para precios y disponibilidad.",
      },
    ],
    welcomeTitle: "Bienvenido a Greenfield Lawn Care",
    welcome: [
      "Greenfield Lawn Care es una empresa familiar que atiende la zona desde 1998. Buscamos dar un buen servicio a un precio competitivo.",
      "Si necesitas césped, jardinería o pavimento, estamos para ayudarte. Recorre el sitio y contáctanos si tienes preguntas.",
    ],
    blogTitle: "Del blog",
    blogPost: "5 consejos para un césped más verde esta primavera",
    blogMore: "Leer más",
    blogLess: "Cerrar",
    blogBody:
      "La primavera es un buen momento para pensar en el césped. Riega seguido, corta a la altura correcta y llama a un profesional para más información. Gracias por visitar nuestro blog.",
    searchLabel: "Buscar",
    searchButton: "Buscar",
    searchEmpty: "Nada coincidió con esa búsqueda.",
    recentTitle: "Entradas recientes",
    recent: ["5 consejos para un césped más verde esta primavera", "¡Hola, mundo!"],
    categoriesTitle: "Categorías",
    categories: ["Césped", "Sin categoría"],
    metaTitle: "Meta",
    login: "Acceder",
    rss: "RSS de las entradas",
    loginNote: "Sitio de ejemplo. No hay acceso.",
    aboutTitle: "Nosotros",
    about: [
      "Greenfield Lawn Care es una empresa familiar desde 1998. Nos importa el trabajo bien hecho y que el cliente quede conforme.",
      "El equipo está para cubrir lo que necesites afuera. Llama hoy para más información sobre nuestros servicios.",
    ],
    servicesTitle: "Nuestros servicios",
    servicesIntro:
      "Abajo está la lista de servicios. Usa el botón para contactar a la oficina.",
    contactTitle: "Contáctanos",
    contactIntro: "Llena el formulario y te responderemos lo antes posible.",
    phoneLabel: "Teléfono",
    phone: "(555) 555-0199",
    address: "123 Main Street, Springfield",
    form: {
      name: "Nombre",
      email: "Correo",
      message: "Mensaje",
      send: "Enviar",
      error: "Completa los campos obligatorios.",
      thanks: "Gracias. Tu mensaje fue enviado.",
    },
    footer: "Creado con WordPress",
  },
  nx: {
    domain: "greenfieldlawncare.com",
    menu: "Menú",
    close: "Cerrar menú",
    home: "Inicio",
    quote: "Pedir presupuesto",
    call: "Llamar",
    trade: "Césped",
    kicker: "Diseño y obra",
    title: "Jardines que se ven terminados.",
    lede: "Diseño, obra y cuidado de temporada con un solo equipo.",
    rating: "4.9 de vecinos en la ruta",
    trust: ["Con licencia", "Asegurados", "Equipo local"],
    stats: [
      { value: "1998", label: "Familia" },
      { value: "5", label: "Pueblos" },
      { value: "Semanal", label: "Día de corte" },
    ],
    introEyebrow: "Un equipo",
    introTitle: "Lo dibuja, lo construye y lo corta la misma gente.",
    introBody:
      "La obra no pasa a otra empresa. Greenfield sigue en el césped después de que el patio está puesto.",
    introLink: "Sobre el equipo",
    marquee: ["Césped", "Fertilización", "Aireación", "Diseño", "Pavimento", "Riego", "Con licencia", "Asegurados"],
    servicesLabel: "Servicios",
    servicesLead: "Ocho formas de trabajar un jardín. Un presupuesto cubre las que hacen falta.",
    featuredLabel: "Antes de cavar",
    alsoLabel: "También en la camioneta",
    processTitle: "Cómo empieza un trabajo",
    steps: [
      {
        title: "Recorrer el jardín",
        body: "Medimos el césped, las camas y lo que quieres dejar igual.",
      },
      {
        title: "Ponerle precio al dibujo",
        body: "El presupuesto nombra el trabajo. Puedes recorrer el plano antes de que alguien empiece.",
      },
      {
        title: "Quedarse en la ruta",
        body: "Después de la obra, el corte y la limpieza siguen con este equipo.",
      },
    ],
    spotlightKicker: "Springfield",
    spotlightTitle: "Un patio del mismo dibujo.",
    spotlightBody: "El adoquín, el camino y las camas estaban en el plano que el dueño aprobó.",
    spotlightLink: "Ver trabajo reciente",
    reviewsTitle: "De jardines en la ruta",
    reviews: [
      {
        quote: "Recorrieron el jardín, dejaron un plano y construyeron eso.",
        by: "Propietario, Springfield",
      },
      {
        quote: "El corte llega el día que dijeron. El bordeado y el soplado van en esa visita.",
        by: "Propietario, Riverside",
      },
    ],
    areasLabel: "Pueblos de la ruta",
    areasLead: "El diseño y la ruta semanal paran aquí.",
    areasLink: "Ver zonas",
    ctaTitle: "Que recorramos el jardín.",
    ctaBody: "Dinos el pueblo y qué hace falta. Llamamos para acordar la hora.",
    phoneLabel: "Llamar",
    phone: "(555) 555-0199",
    aboutNav: "Nosotros",
    galleryNav: "Galería",
    areasNav: "Zonas",
    contactNav: "Contacto",
    services: [
      {
        id: "lawn" as const,
        path: "/lawn-care",
        nav: "Césped",
        card: "Corte, bordeado y soplado el mismo día de la semana.",
        title: "Césped en Springfield",
        lede: "Corte, bordeado y soplado el mismo día de cada semana.",
        includes: [
          "Corte semanal en temporada",
          "Bordeado de caminos y camas",
          "Recortes fuera de las superficies duras",
          "Ruta por cinco pueblos",
        ],
        faqs: [
          {
            q: "¿La visita es semanal?",
            a: "En temporada, sí. El clima puede mover el día. No sale de la ruta.",
          },
          {
            q: "¿Cortan fuera de Springfield?",
            a: "La ruta incluye Riverside, Fairview, Greenville y Oakwood.",
          },
        ],
      },
      {
        id: "feed" as const,
        path: "/fertilization",
        nav: "Fertilización",
        card: "Cinco visitas de abono y maleza, en su propia ruta.",
        title: "Fertilización y control de maleza",
        lede: "Cinco visitas, a tiempo con la temporada, en vez de una sola aplicación.",
        includes: [
          "Abono de inicio de primavera",
          "Control de maleza de hoja ancha",
          "Revisión de verano por gusanos",
          "Abono de otoño antes del reposo",
        ],
        faqs: [
          {
            q: "¿Es la misma visita que el corte?",
            a: "No. La fertilización es otra ruta, con su propio presupuesto.",
          },
          {
            q: "¿Tratan todo el jardín?",
            a: "El plan cubre el césped. Las camas y el pavimento quedan fuera.",
          },
        ],
      },
      {
        id: "aeration" as const,
        path: "/aeration",
        nav: "Aireación",
        card: "Tapones a inicios de otoño y semilla en las zonas ralas.",
        title: "Aireación y siembra",
        lede: "Tapones a inicios de otoño, y semilla en las zonas ralas.",
        includes: [
          "Aireación con tapones",
          "Semilla en zonas gastadas",
          "Una capa ligera donde el suelo es pobre",
          "Una revisión después del primer corte",
        ],
        faqs: [
          {
            q: "¿Cuándo airean?",
            a: "A inicios de otoño, con el suelo todavía tibio.",
          },
          {
            q: "¿Puedo cortar justo después?",
            a: "Espera a que la semilla prenda. El equipo te dice cuándo.",
          },
        ],
      },
      {
        id: "cleanup" as const,
        path: "/seasonal-cleanup",
        nav: "Limpieza",
        card: "Camas recortadas, hojas retiradas, jardín de temporada.",
        title: "Limpieza de primavera y otoño",
        lede: "Camas recortadas, hojas retiradas y el jardín listo para abrir o cerrar la temporada.",
        includes: ["Recorte de camas", "Retiro de hojas", "Acarreo", "Un recorrido cuando el equipo termina"],
        faqs: [
          {
            q: "¿La limpieza va con el corte?",
            a: "El soplado semanal sí. Una limpieza de temporada es otra visita.",
          },
          {
            q: "¿Se llevan los restos?",
            a: "Sí. Salen con el equipo.",
          },
        ],
      },
      {
        id: "design" as const,
        path: "/landscape-design",
        nav: "Diseño",
        card: "Un plano medido que puedes recorrer antes de cavar.",
        title: "Diseño de jardín en Springfield",
        lede: "Un plano medido que puedes recorrer antes de que el equipo empiece.",
        includes: [
          "Recorrido y medidas del terreno",
          "Césped, camas y plantas ubicados",
          "El pavimento en el mismo dibujo",
          "Un presupuesto atado a ese plano",
        ],
        faqs: [
          {
            q: "¿Diseñan antes de construir?",
            a: "Sí. El precio sigue el dibujo.",
          },
          {
            q: "¿En qué pueblos diseñan?",
            a: "Springfield, Riverside, Fairview, Greenville y Oakwood.",
          },
        ],
      },
      {
        id: "planting" as const,
        path: "/planting",
        nav: "Plantación",
        card: "Arbustos, perennes y mulch según el plano.",
        title: "Plantación y mulch",
        lede: "Arbustos, perennes y mulch según el plano, no elegidos al azar en el vivero.",
        includes: ["Arbustos y perennes", "Borde de camas", "Mulch a una profundidad fija", "Una nota de riego para la primera temporada"],
        faqs: [
          {
            q: "¿Yo elijo las plantas?",
            a: "Puedes. O el plano las nombra y el equipo las compra.",
          },
          {
            q: "¿Cuándo plantan?",
            a: "Primavera y otoño. En verano, solo si el riego ya está.",
          },
        ],
      },
      {
        id: "hardscape" as const,
        path: "/hardscaping",
        nav: "Pavimento",
        card: "Patios, caminos y muros con el mismo equipo.",
        title: "Patios, caminos y muros",
        lede: "Adoquín y piedra, con el mismo equipo que dibujó el plano.",
        includes: ["Patios de adoquín", "Caminos de entrada", "Muros de contención", "Escalones y bordes"],
        faqs: [
          {
            q: "¿Pueden construir un plano que ya tengo?",
            a: "Sí. Si quieres que el equipo lo dibuje, empieza por diseño.",
          },
          {
            q: "¿Cuándo instalan los patios?",
            a: "Durante la temporada de obra. El presupuesto dice la ventana.",
          },
        ],
      },
      {
        id: "irrigation" as const,
        path: "/irrigation",
        nav: "Riego",
        card: "Zonas nuevas donde el césped las pide, y la purga.",
        title: "Riego e hibernación",
        lede: "Zonas nuevas donde el césped las necesita, y una purga antes de la primera helada fuerte.",
        includes: ["Trazo de zonas", "Cambio de aspersores", "Ajuste del controlador", "Purga de otoño"],
        faqs: [
          {
            q: "¿Atienden sistemas que no instalaron?",
            a: "Sí. El presupuesto empieza con un recorrido de las zonas que ya están.",
          },
          {
            q: "¿Cuándo es la purga?",
            a: "Antes de la primera helada fuerte, en un día acordado.",
          },
        ],
      },
    ],
    includedLabel: "Qué incluye",
    faqLabel: "Preguntas",
    otherLabel: "Otros servicios",
    townsTitle: "Pueblos que cubre este equipo",
    townsLede: "Diseño, pavimento y césped con un solo equipo en estos pueblos.",
    towns: [
      { name: "Springfield", body: "Diseño, patios y la ruta semanal de corte." },
      { name: "Riverside", body: "Pavimento y césped de temporada." },
      { name: "Fairview", body: "Jardines más chicos, con el plano primero." },
      { name: "Greenville", body: "En la ruta de corte y limpieza." },
      { name: "Oakwood", body: "Césped y trabajos de pavimento más chicos." },
    ],
    galleryTitle: "Trabajo reciente",
    galleryLede: "Patios, caminos y césped que terminó el mismo equipo.",
    projects: [
      { title: "Patio de adoquín", place: "Springfield", image: "patio" as const, focus: "center 48%" },
      { title: "Camino y camas", place: "Riverside", image: "walk" as const, focus: "center 18%" },
      { title: "Ruta semanal", place: "Fairview", image: "house" as const, focus: "center 70%" },
      { title: "Muro de contención", place: "Springfield", image: "wall" as const, focus: "center 55%" },
    ],
    aboutTitle: "Un equipo desde 1998",
    about: [
      "Greenfield dibuja el plano, construye el pavimento y sigue en la ruta del césped. Son las mismas personas desde la primera visita hasta el corte semanal.",
      "Con licencia y seguro. El trabajo está en Springfield y los pueblos de al lado.",
    ],
    contactTitle: "Pedir presupuesto",
    contactLede: "Dinos el pueblo y el trabajo. Llamamos para acordar una visita al jardín.",
    form: {
      name: "Nombre",
      phone: "Teléfono",
      email: "Correo",
      need: "¿Qué necesitas?",
      message: "El jardín, en una frase",
      send: "Pedir presupuesto",
      error: "Agrega un nombre y una forma de contacto.",
      thanks: "Este formulario es parte del ejemplo. No se envió nada.",
    },
    footerBlurb: "Diseño, pavimento y césped con un solo equipo.",
    since: "Familia desde 1998",
    footerServices: "Servicios",
    footerCompany: "Empresa",
    footerAreas: "Zonas",
  },
};

export const greenfieldExamples = localeContent({
  en,
  "es-419": es,
});

export type GreenfieldExampleCopy = (typeof greenfieldExamples)["en"];
export type WpExampleCopy = GreenfieldExampleCopy["wp"];
export type NxExampleCopy = GreenfieldExampleCopy["nx"];
export type WpPageId = WpExampleCopy["nav"][number]["id"];
export type NxServiceId = NxExampleCopy["services"][number]["id"];
export type NxPageId = "home" | "areas" | "gallery" | "about" | "contact" | NxServiceId;

export function getGreenfieldExampleCopy(locale: Locale): GreenfieldExampleCopy {
  return greenfieldExamples[locale] ?? greenfieldExamples.en;
}
